In [1]:
import pandas as pd
features = pd.read_csv('test.csv')
features.head(5)


Number in the queue/DeptNumber  Shift (M/A/E)  Queue Type (Reg  \
0                             102              3                1   
1                             103              3                1   
2                             102              3                1   
3                             101              1                1   
4                             102              1                1   

   Service Point   Created Queue Hours  Created Queue Day of Week  \
0               3                   11                          7   
1               3                   19                          1   
2               4                   15                          7   
3               3                   15                          3   
4               1                   14                          7   

   Waiting Duration  Number of Waiting Queue  Arrival Rate  Service Rate  
0                16                        1             9            10  
1                26                        4            10             8  
2                33                        8             7             9  
3                33                        6             3             8  
4                21                        1             3             8

In [2]:
print('The shape of our features is:', features.shape)

The shape of our features is: (70, 10)


In [3]:
features.describe()

Number in the queue/DeptNumber  Shift (M/A/E)  Queue Type (Reg  \
count                       70.000000      70.000000        70.000000   
mean                       223.400000       2.128571         2.214286   
std                         84.834434       0.899620         0.849430   
min                        101.000000       1.000000         1.000000   
25%                        103.000000       1.000000         1.000000   
50%                        203.000000       2.000000         2.000000   
75%                        302.000000       3.000000         3.000000   
max                        303.000000       3.000000         3.000000   

       Service Point   Created Queue Hours  Created Queue Day of Week  \
count       70.000000            70.000000                  70.000000   
mean         2.571429            13.957143                   4.000000   
std          1.136629             3.827572                   1.985454   
min          1.000000             8.000000                   1.000000   
25%          2.000000            11.000000                   2.000000   
50%          3.000000            14.000000                   4.000000   
75%          4.000000            17.000000                   6.000000   
max          4.000000            20.000000                   7.000000   

       Waiting Duration  Number of Waiting Queue  Arrival Rate  Service Rate  
count         70.000000                70.000000     70.000000     70.000000  
mean          40.071429                 4.914286      6.671429     31.214286  
std           13.288680                 2.887970      2.557860     19.341997  
min           15.000000                 0.000000      3.000000      1.000000  
25%           30.000000                 3.000000      4.000000     13.250000  
50%           40.000000                 5.000000      7.000000     30.500000  
75%           51.750000                 7.000000      9.000000     47.750000  
max           60.000000                10.000000     10.000000     65.000000

In [4]:
import numpy as np
# Labels are the values we want to predict
labels = np.array(features['Waiting Duration'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('Waiting Duration', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [5]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [6]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (52, 9)
Training Labels Shape: (52,)
Testing Features Shape: (18, 9)
Testing Labels Shape: (18,)


In [7]:
# # baseline_preds = test_features[:, feature_list.index('Average Wait Time')]
# # Baseline errors, and display average baseline error
# baseline_errors = abs(baseline_preds - test_labels)
# print('Average baseline error: ', round(np.mean(baseline_errors), 2))

In [8]:
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [9]:
predictions = rf.predict(test_features)
print(test_features)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

[[202   3   2   2   9   1   3   8  18]
 [102   3   1   3  11   7   1   9  10]
 [301   3   3   4  16   6   5   7  45]
 [102   1   1   1  14   7   1   3   8]
 [302   2   3   3  16   6   6   5  50]
 [102   1   1   3  19   3   2   5  14]
 [101   3   1   1  13   2   8   5   6]
 [202   1   2   2  12   1   5   8  29]
 [301   3   3   4   8   4   9   8  41]
 [103   3   1   3  14   2   9   3   8]
 [203   2   2   4  12   4   7   4  27]
 [102   3   1   3  11   4   4  10   4]
 [302   3   3   4  20   2   5   8  63]
 [101   3   1   3  13   4   3  10   2]
 [303   1   3   4   9   6   4   7  58]
 [202   3   2   1  13   7   1   7  26]
 [301   2   3   4  13   6   3   5  54]
 [201   3   2   1  18   4   1   5  31]]
Mean Absolute Error: 13.41 degrees.


In [10]:
mape = 100 * (errors / test_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 58.9 %.


In [11]:
y=np.array([[103],[123]])
print(type(y))

<class 'numpy.ndarray'>


In [12]:
y.reshape(-1,1)

array([[103],
       [123]])

In [15]:
rf.predict([[4,3,2,1,20,2,12,5,65]])

array([43.795])